/**
 * Monitor file (tests-data.js) read/write helpers.
 *
 * The monitor file uses `var testData = {...};` format so it can be
 * loaded directly by the dashboard HTML via <script> tag.
 */

const fs = require('fs');
const path = require('path');

const MONITOR_FILE = path.join(__dirname, '..', 'monitor', 'tests-data.js');

const TESTDATA_REGEX = /var testData\s*=\s*(\{[\s\S]*\});?\s*$/;

const DEFAULT_DATA = {
    lastUpdate: '',
    agentStatus: {
        isRunning: false,
        currentAction: '',
        lastAction: null,
        finished: false,
        startedAt: null,
        finishedAt: null,
    },
    summary: { total: 0, passed: 0, failed: 0, blocked: 0, inProgress: 0 },
    currentTest: null,
    tests: [],
};

/**
 * Read and parse tests-data.js. Returns the testData object.
 * Returns DEFAULT_DATA on any error.
 */
function readTestsData(filePath) {
    const target = filePath || MONITOR_FILE;
    try {
        const content = fs.readFileSync(target, 'utf8');
        const match = content.match(TESTDATA_REGEX);
        if (match) return JSON.parse(match[1]);
    } catch (e) { /* fall through */ }
    return { ...DEFAULT_DATA, agentStatus: { ...DEFAULT_DATA.agentStatus }, summary: { ...DEFAULT_DATA.summary } };
}

/**
 * Write testData object to tests-data.js.
 * Automatically updates lastUpdate timestamp.
 */
function writeTestsData(data, filePath) {
    const target = filePath || MONITOR_FILE;
    data.lastUpdate = new Date().toISOString().slice(0, 19);
    const content = `// Auto-generated by Test Monitor\nvar testData = ${JSON.stringify(data, null, 2)};\n`;
    fs.writeFileSync(target, content, 'utf8');
}

module.exports = { readTestsData, writeTestsData, MONITOR_FILE, DEFAULT_DATA };
