#!/usr/bin/env node
/**
 * ORKIESTRATOR TESTOW - Caly workflow jako kod
 *
 * Schemat:
 *   1. Pipeline (batch coded tests) -> pw-coded-results.json
 *   2. Auto-tester (NLP remaining)  -> direct Playwright
 *   3. Zapis wynikow do GSheets     -> MCP service account API
 *
 * Uzycie:
 *   node run-tests.js                          # Wszystkie testy
 *   node run-tests.js --category=LOGIN         # Tylko kategoria (aliasy dzialaja)
 *   node run-tests.js --category=TABLE         # TABELA ATRYBUTOW
 *   node run-tests.js --coded-only             # Tylko coded (bez NLP)
 *   node run-tests.js --nlp-only               # Tylko NLP (bez pipeline)
 *   node run-tests.js --no-sheets              # Bez zapisu do GSheets
 *   node run-tests.js --test=TC-LOGIN-001      # Pojedynczy test
 *
 * Stop: przycisk w monitorze (localhost:8081) lub:  node create-stop-signal.js
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

// ==================== PATHS ====================

const AGENT_ROOT = path.resolve(__dirname, '..');
const SCRIPTS_DIR = __dirname;
const DATA_DIR = path.join(AGENT_ROOT, 'data');
const MONITOR_DIR = path.join(AGENT_ROOT, 'monitor');
const CONFIG_DIR = path.join(AGENT_ROOT, 'config');

const REMAINING_PATH = path.join(DATA_DIR, 'remaining-tests.json');
const TESTS_DATA_PATH = path.join(MONITOR_DIR, 'tests-data.js');
const STOP_SIGNAL_PATH = path.join(MONITOR_DIR, 'stop-signal.txt');
const SHEET_CONFIG_PATH = path.join(CONFIG_DIR, 'sheet-config.json');
const PW_RESULTS_PATH = path.join(DATA_DIR, 'pw-coded-results.json');

// ==================== CLI ARGS ====================

const args = process.argv.slice(2);
const CODED_ONLY = args.includes('--coded-only');
const NLP_ONLY = args.includes('--nlp-only');
const NO_SHEETS = args.includes('--no-sheets');
const categoryArg = args.find(a => a.startsWith('--category='));
const testIdArg = args.find(a => a.startsWith('--test='));
const CATEGORY = categoryArg ? categoryArg.split('=')[1] : null;
const SINGLE_TEST = testIdArg ? testIdArg.split('=')[1] : null;

// ==================== UTILS ====================

function log(msg) {
    const time = new Date().toLocaleTimeString('pl-PL');
    console.log(`[${time}] ${msg}`);
}

function checkStop() {
    try {
        if (fs.existsSync(STOP_SIGNAL_PATH)) {
            return fs.readFileSync(STOP_SIGNAL_PATH, 'utf8').includes('STOP');
        }
    } catch {}
    return false;
}

function clearStop() {
    try { fs.unlinkSync(STOP_SIGNAL_PATH); } catch {}
}

function loadSheetConfig() {
    try {
        return JSON.parse(fs.readFileSync(SHEET_CONFIG_PATH, 'utf8'));
    } catch {}
    return {
        sheetId: '1wFlv0KrT4JNTXAnGO4mwtDXPkh2dIxQzfM0VCXxA1jA',
        sheetTitle: 'Testy_Lista',
        tabName: 'Arkusz1'
    };
}

// ==================== MONITOR UPDATE ====================

function readMonitorData() {
    try {
        const raw = fs.readFileSync(TESTS_DATA_PATH, 'utf8');
        const match = raw.match(/var testData = ({[\s\S]*});?\s*$/);
        if (match) return JSON.parse(match[1]);
    } catch {}
    return null;
}

function writeMonitorData(data) {
    const content = `// Auto-generated by run-tests.js\nvar testData = ${JSON.stringify(data, null, 2)};\n`;
    fs.writeFileSync(TESTS_DATA_PATH, content, 'utf8');
}

// ==================== PHASE 1: PIPELINE ====================

function runPipeline() {
    return new Promise((resolve, reject) => {
        const pipelineArgs = ['test-pipeline.js'];

        if (CATEGORY) pipelineArgs.push(`--category=${CATEGORY}`);
        if (NO_SHEETS) pipelineArgs.push('--no-write');

        log(`Faza 1: node ${pipelineArgs.join(' ')}`);

        const child = spawn('node', pipelineArgs, {
            cwd: SCRIPTS_DIR,
            stdio: ['ignore', 'pipe', 'inherit'],
            shell: true,
        });

        let stdout = '';
        child.stdout.on('data', chunk => stdout += chunk.toString());

        child.on('exit', (code) => {
            log(`Pipeline zakonczony (kod: ${code})`);
            try {
                const result = JSON.parse(stdout);
                resolve(result);
            } catch (e) {
                log(`Warning: nie udalo sie sparsowac JSON z pipeline`);
                resolve({ ok: false, error: 'JSON parse error', coded: { results: [] }, remaining: { tests: [] } });
            }
        });

        child.on('error', (err) => {
            log(`Pipeline error: ${err.message}`);
            reject(err);
        });
    });
}

// ==================== PHASE 2: NLP TESTS ====================

function runAutoTester() {
    return new Promise((resolve) => {
        const testerArgs = ['auto-tester.js', '--remaining'];

        log(`Faza 2: node ${testerArgs.join(' ')}`);

        const child = spawn('node', testerArgs, {
            cwd: SCRIPTS_DIR,
            stdio: 'inherit',
            shell: true,
        });

        child.on('exit', (code) => {
            log(`Auto-tester zakonczony (kod: ${code})`);
            resolve(code || 0);
        });

        child.on('error', (err) => {
            log(`Auto-tester error: ${err.message}`);
            resolve(1);
        });
    });
}

// ==================== PHASE 3: GSHEETS WRITE (Sheets API v4) ====================

const sheetsWriter = require('../lib/sheets-writer');

async function writeResultsToGSheets(pipelineResult) {
    if (NO_SHEETS) {
        log('Pomijam zapis do GSheets (--no-sheets)');
        return;
    }

    const config = loadSheetConfig();
    if (!config.sheetId) {
        log('Brak sheetId - pomijam GSheets');
        return;
    }

    // Zbierz wyniki z monitora (coded + NLP)
    const monitorData = readMonitorData();
    if (!monitorData || !monitorData.tests || monitorData.tests.length === 0) {
        log('Brak wynikow w monitorze do zapisania');
        return;
    }

    // Odczytaj row mapping z remaining-tests.json lub pipeline output
    const rowMap = {};

    // Z pipeline output
    if (pipelineResult?.coded?.results) {
        for (const r of pipelineResult.coded.results) {
            if (r.code && r.row) rowMap[r.code] = r.row;
        }
    }
    if (pipelineResult?.remaining?.tests) {
        for (const r of pipelineResult.remaining.tests) {
            if (r.id && r.row) rowMap[r.id] = r.row;
        }
    }

    // Z remaining-tests.json (fallback)
    try {
        const remaining = JSON.parse(fs.readFileSync(REMAINING_PATH, 'utf8'));
        if (remaining.tests) {
            for (const t of remaining.tests) {
                if (t.id && t.row) rowMap[t.id] = t.row;
            }
        }
    } catch {}

    // Przygotuj results array for batch update
    const results = [];
    for (const test of monitorData.tests) {
        const row = rowMap[test.code];
        if (!row) continue;

        const status = (test.status || '').toUpperCase();
        if (!status || status === 'PENDING') continue;

        results.push({
            code: test.code,
            status,
            resultText: test.resultText || test.notes || test.error || '',
            finishedAtDisplay: test.finishedAtDisplay || new Date().toLocaleString('pl-PL'),
            source: test.source || 'run-tests',
        });
    }

    if (results.length === 0) {
        log('Brak wynikow z row mapping do GSheets');
        return;
    }

    log(`Zapisuje ${results.length} wynikow do GSheets (API v4)...`);
    const { written, errors } = await sheetsWriter.batchUpdateResults(results, rowMap);
    log(`GSheets: zapisano ${written}/${results.length} (${errors} bledow)`);
}

// ==================== MAIN ====================

async function main() {
    const t0 = Date.now();

    log('========================================');
    log('  ORKIESTRATOR TESTOW');
    log('========================================');
    if (CATEGORY) log(`  Kategoria: ${CATEGORY}`);
    if (SINGLE_TEST) log(`  Test: ${SINGLE_TEST}`);
    if (CODED_ONLY) log(`  Tryb: coded-only`);
    if (NLP_ONLY) log(`  Tryb: nlp-only`);
    log('');

    // Wyczysc stop signal
    clearStop();

    let pipelineResult = null;

    // === FAZA 1: Pipeline (coded batch) ===
    if (!NLP_ONLY) {
        if (checkStop()) { log('STOP przed pipeline'); return; }

        try {
            pipelineResult = await runPipeline();

            if (pipelineResult.ok) {
                const c = pipelineResult.coded;
                log(`Pipeline OK: ${c.passed}P/${c.failed}F/${c.blocked || 0}B coded`);
                log(`Remaining: ${pipelineResult.remaining.total} (${pipelineResult.remaining.learned} learned, ${pipelineResult.remaining.nlp} NLP)`);
            } else {
                log(`Pipeline FAILED: ${pipelineResult.error}`);
            }
        } catch (e) {
            log(`Pipeline CRASH: ${e.message}`);
        }
    }

    // === FAZA 2: NLP tests (auto-tester) ===
    if (!CODED_ONLY) {
        if (checkStop()) { log('STOP przed NLP'); return; }

        // Sprawdz czy sa remaining tests
        let hasRemaining = false;
        try {
            const data = JSON.parse(fs.readFileSync(REMAINING_PATH, 'utf8'));
            hasRemaining = data.tests && data.tests.length > 0;
            if (hasRemaining) {
                log(`\n${data.tests.length} testow NLP/LEARNED do wykonania`);
            }
        } catch {}

        if (hasRemaining) {
            const exitCode = await runAutoTester();
            if (exitCode !== 0) {
                log('Auto-tester zakonczyl z bledami');
            }
        } else if (!NLP_ONLY) {
            log('Brak remaining tests - wszystko pokryte przez Playwright');
        } else {
            log('Brak remaining-tests.json - uruchom najpierw pipeline');
        }
    }

    // === FAZA 3: Zapis do GSheets ===
    if (checkStop()) { log('STOP przed GSheets'); }
    else {
        await writeResultsToGSheets(pipelineResult);
    }

    // === PODSUMOWANIE ===
    const elapsed = Math.round((Date.now() - t0) / 1000);
    const monitorData = readMonitorData();
    const summary = monitorData?.summary || {};

    // Oznacz koniec sesji w monitorze
    if (monitorData) {
        monitorData.agentStatus = monitorData.agentStatus || {};
        monitorData.agentStatus.isRunning = false;
        monitorData.agentStatus.finished = true;
        monitorData.agentStatus.finishedAt = new Date().toISOString().slice(0, 19);
        monitorData.agentStatus.currentAction = `Zakonczono (${elapsed}s)`;
        writeMonitorData(monitorData);
    }

    log('\n========================================');
    log('  PODSUMOWANIE');
    log('========================================');
    log(`  Total:    ${summary.total || 0}`);
    log(`  Passed:   ${summary.passed || 0}`);
    log(`  Failed:   ${summary.failed || 0}`);
    log(`  Blocked:  ${summary.blocked || 0}`);
    log(`  Pending:  ${summary.pending || 0}`);
    log(`  Czas:     ${elapsed}s`);
    log('========================================');
}

main().catch(err => {
    console.error('CRASH:', err.message);
    process.exit(1);
});
