/**
 * E2E Test Server - standalone mikroserwis
 *
 * API:
 *   POST /api/start    - uruchom testy { category?, testId? }
 *   POST /api/stop     - zatrzymaj testy
 *   GET  /api/status   - { running, finished, elapsed }
 *   GET  /api/results  - { summary, tests[] }
 *   POST /api/reset    - reset sesji
 *   GET  /             - dashboard HTML (monitor)
 *
 * Deploy: Docker + K8s Deployment + Ingress
 * Auth: X-API-Key header
 */

const http = require('http');
const fs = require('fs');
const path = require('path');
const { spawn, execSync } = require('child_process');

const PORT = process.env.PORT || 8081;
const API_KEY = process.env.TESTER_API_KEY || '';
const IS_LINUX = process.platform !== 'win32';

const MONITOR_DIR = path.join(__dirname, '..', 'monitor');
const CONFIG_FILE = path.join(__dirname, '..', 'config', 'sheet-config.json');
const STOP_FILE = path.join(__dirname, '..', 'monitor', 'stop-signal.txt');
const TESTS_DATA_FILE = path.join(__dirname, '..', 'monitor', 'tests-data.js');
const REMAINING_FILE = path.join(__dirname, '..', 'data', 'remaining-tests.json');

let testerProcess = null;

// ==================== UTILS ====================

function log(msg) {
    const time = new Date().toLocaleTimeString('pl-PL');
    console.log(`[${time}] ${msg}`);
}

function parseBody(req) {
    return new Promise((resolve, reject) => {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            try { resolve(body ? JSON.parse(body) : {}); }
            catch { reject(new Error('Invalid JSON')); }
        });
        req.on('error', reject);
    });
}

function readTestsData() {
    try {
        const raw = fs.readFileSync(TESTS_DATA_FILE, 'utf8');
        const match = raw.match(/var testData = ({[\s\S]*});?\s*$/);
        if (match) return JSON.parse(match[1]);
    } catch {}
    return null;
}

function writeTestsData(data) {
    const content = `// Auto-generated by server.js\nvar testData = ${JSON.stringify(data, null, 2)};\n`;
    fs.writeFileSync(TESTS_DATA_FILE, content, 'utf8');
}

const MIME_TYPES = {
    '.html': 'text/html; charset=utf-8',
    '.js': 'application/javascript; charset=utf-8',
    '.css': 'text/css; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.svg': 'image/svg+xml',
    '.png': 'image/png',
    '.ico': 'image/x-icon'
};

// ==================== RESET ====================

function resetTestsData(sheetId, sheetUrl, sheetTitle, startMode) {
    const initialData = {
        lastUpdate: startMode ? new Date().toISOString().slice(0, 19) : null,
        sheetId: sheetId || '',
        sheetUrl: sheetUrl || '',
        sheetTitle: sheetTitle || '',
        agentStatus: {
            isRunning: !!startMode,
            currentAction: startMode ? 'Inicjalizacja...' : '',
            lastAction: null,
            finished: false,
            startedAt: startMode ? new Date().toISOString().slice(0, 19) : null,
            finishedAt: null
        },
        summary: { total: 0, passed: 0, failed: 0, blocked: 0, inProgress: 0, pending: 0, skipped: 0 },
        currentTest: null,
        tests: []
    };
    writeTestsData(initialData);
    log('Reset tests-data.js' + (startMode ? ' (start)' : ' (clean)'));
}

// ==================== PROCESS MANAGEMENT ====================

function killTesterProcess() {
    if (testerProcess) {
        log('Zatrzymuję proces testera (PID: ' + testerProcess.pid + ')...');
        try {
            if (IS_LINUX) {
                // Linux/Docker: kill process group
                process.kill(-testerProcess.pid, 'SIGKILL');
            } else {
                // Windows: kill process tree
                execSync(`taskkill /F /T /PID ${testerProcess.pid}`, { stdio: 'ignore' });
            }
        } catch (e) {
            log('Warning: kill failed: ' + e.message);
        }
        testerProcess = null;
    }
    try { fs.unlinkSync(STOP_FILE); } catch {}
}

function killExternalProcesses() {
    try {
        if (IS_LINUX) {
            execSync("pkill -f 'test-pipeline|auto-tester|playwright test' 2>/dev/null || true", { stdio: 'ignore' });
        } else {
            execSync('wmic process where "commandline like \'%test-pipeline%\' and name=\'node.exe\'" call terminate 2>nul', { stdio: 'ignore' });
            execSync('wmic process where "commandline like \'%auto-tester%\' and name=\'node.exe\'" call terminate 2>nul', { stdio: 'ignore' });
            execSync('wmic process where "commandline like \'%playwright test%\' and name=\'node.exe\'" call terminate 2>nul', { stdio: 'ignore' });
        }
    } catch {}
}

function checkStopSignal() {
    try {
        if (fs.existsSync(STOP_FILE)) {
            return fs.readFileSync(STOP_FILE, 'utf8').includes('STOP');
        }
    } catch {}
    return false;
}

// ==================== START TESTS ====================

function startTester(config) {
    killTesterProcess();
    try { fs.unlinkSync(STOP_FILE); } catch {}

    const sheetId = config.sheetId || '';
    const sheetUrl = config.sheetUrl || `https://docs.google.com/spreadsheets/d/${sheetId}/edit`;
    const sheetTitle = config.sheetTitle || '';
    const category = config.category || '';
    const testId = config.testId || '';

    resetTestsData(sheetId, sheetUrl, sheetTitle, true);

    // Pojedynczy test
    if (testId) {
        log(`Start: pojedynczy test ${testId}`);
        const child = spawn('node', ['auto-tester.js', `--test=${testId}`], {
            cwd: __dirname, stdio: 'inherit', shell: true,
            detached: IS_LINUX,
        });
        testerProcess = child;
        child.on('exit', () => { testerProcess = null; });
        child.on('error', () => { testerProcess = null; });
        return { started: true, mode: 'single', testId };
    }

    // Pipeline (coded batch) + auto-tester (NLP remaining)
    const pipelineArgs = ['test-pipeline.js'];
    if (category) pipelineArgs.push(`--category=${category}`);
    if (process.env.HEADLESS === '1') pipelineArgs.push('--headless');

    log(`Start: pipeline ${pipelineArgs.join(' ')}`);

    const phase1 = spawn('node', pipelineArgs, {
        cwd: __dirname, stdio: 'inherit', shell: true,
        detached: IS_LINUX,
    });
    testerProcess = phase1;

    phase1.on('exit', (code) => {
        log(`Pipeline zakończony (kod: ${code})`);

        if (checkStopSignal()) {
            log('STOP signal - pomijam Fazę 2');
            testerProcess = null;
            return;
        }

        // Sprawdź remaining
        let hasRemaining = false;
        try {
            const data = JSON.parse(fs.readFileSync(REMAINING_FILE, 'utf8'));
            hasRemaining = data.tests && data.tests.length > 0;
        } catch {}

        if (!hasRemaining) {
            log('Brak remaining - wszystko pokryte Playwright');
            testerProcess = null;
            return;
        }

        // Faza 2: NLP
        log('Faza 2: auto-tester (remaining)...');
        const phase2 = spawn('node', ['auto-tester.js', '--remaining'], {
            cwd: __dirname, stdio: 'inherit', shell: true,
            detached: IS_LINUX,
        });
        testerProcess = phase2;
        phase2.on('exit', () => { testerProcess = null; });
        phase2.on('error', () => { testerProcess = null; });
    });

    phase1.on('error', (err) => {
        log(`Pipeline error: ${err.message}`);
        testerProcess = null;
    });

    return { started: true, mode: category ? `category:${category}` : 'full' };
}

// ==================== STOP TESTS ====================

function stopTester() {
    fs.writeFileSync(STOP_FILE, 'STOP', 'utf8');
    log('Wysłano STOP');

    // Zaktualizuj monitor
    const data = readTestsData();
    if (data) {
        data.agentStatus = data.agentStatus || {};
        data.agentStatus.isRunning = false;
        data.agentStatus.finished = true;
        data.agentStatus.currentAction = 'ZATRZYMANO';
        data.agentStatus.finishedAt = new Date().toISOString().slice(0, 19);
        writeTestsData(data);
    }

    if (testerProcess) killTesterProcess();
    killExternalProcesses();
}

// ==================== AUTH ====================

function checkAuth(req) {
    if (!API_KEY) return true; // brak klucza = brak auth
    return req.headers['x-api-key'] === API_KEY;
}

// ==================== HTTP SERVER ====================

const server = http.createServer(async (req, res) => {
    // CORS
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-API-Key');

    if (req.method === 'OPTIONS') {
        res.writeHead(200);
        res.end();
        return;
    }

    // Auth for API endpoints
    if (req.url.startsWith('/api/') && !checkAuth(req)) {
        res.writeHead(401, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Unauthorized - provide X-API-Key header' }));
        return;
    }

    // ========== POST /api/start ==========
    if (req.method === 'POST' && req.url === '/api/start') {
        try {
            const body = await parseBody(req);

            // Resolve sheetId from URL if needed
            let sheetId = body.sheetId || '';
            if (body.sheetUrl && !sheetId) {
                const m = body.sheetUrl.match(/\/d\/([a-zA-Z0-9-_]+)/);
                if (m) sheetId = m[1];
            }

            // Default sheet
            if (!sheetId) {
                try {
                    const cfg = JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'));
                    sheetId = cfg.sheetId || '';
                } catch {}
            }

            if (!sheetId) {
                sheetId = '1wFlv0KrT4JNTXAnGO4mwtDXPkh2dIxQzfM0VCXxA1jA';
            }

            const result = startTester({
                sheetId,
                sheetUrl: body.sheetUrl || '',
                sheetTitle: body.sheetTitle || '',
                category: body.category || '',
                testId: body.testId || '',
            });

            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify(result));
        } catch (e) {
            res.writeHead(400, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: e.message }));
        }
        return;
    }

    // ========== POST /api/stop ==========
    if (req.method === 'POST' && req.url === '/api/stop') {
        stopTester();
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: true }));
        return;
    }

    // ========== POST /api/reset ==========
    if (req.method === 'POST' && req.url === '/api/reset') {
        killTesterProcess();
        killExternalProcesses();
        resetTestsData('', '', '', false);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: true }));
        return;
    }

    // ========== GET /api/status ==========
    if (req.method === 'GET' && req.url === '/api/status') {
        const data = readTestsData();
        const isRunning = testerProcess !== null || (data?.agentStatus?.isRunning === true);
        const summary = data?.summary || {};

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({
            running: isRunning,
            finished: data?.agentStatus?.finished || false,
            startedAt: data?.agentStatus?.startedAt || null,
            finishedAt: data?.agentStatus?.finishedAt || null,
            action: data?.agentStatus?.currentAction || '',
            summary: {
                total: summary.total || 0,
                passed: summary.passed || 0,
                failed: summary.failed || 0,
                blocked: summary.blocked || 0,
                pending: summary.pending || 0,
            },
        }));
        return;
    }

    // ========== GET /api/results ==========
    if (req.method === 'GET' && req.url.startsWith('/api/results')) {
        const data = readTestsData();
        const summary = data?.summary || {};
        const tests = (data?.tests || []).map(t => ({
            code: t.code,
            name: t.name,
            category: t.kategoria || t.category || '',
            status: (t.status || '').toUpperCase(),
            result: t.resultText || t.notes || '',
            error: t.error || null,
            duration: t.duration || null,
            finishedAt: t.finishedAtDisplay || t.finishedAt || '',
        }));

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({
            running: data?.agentStatus?.isRunning || false,
            finished: data?.agentStatus?.finished || false,
            startedAt: data?.agentStatus?.startedAt || null,
            finishedAt: data?.agentStatus?.finishedAt || null,
            summary: {
                total: summary.total || 0,
                passed: summary.passed || 0,
                failed: summary.failed || 0,
                blocked: summary.blocked || 0,
                pending: summary.pending || 0,
            },
            tests,
        }));
        return;
    }

    // ========== Static files (monitor dashboard) ==========
    let filePath = req.url === '/' ? '/index.html' : req.url;
    filePath = path.join(MONITOR_DIR, filePath.split('?')[0]);

    const ext = path.extname(filePath);
    const contentType = MIME_TYPES[ext] || 'application/octet-stream';

    fs.readFile(filePath, (err, content) => {
        if (err) {
            res.writeHead(err.code === 'ENOENT' ? 404 : 500);
            res.end(err.code === 'ENOENT' ? 'Not found' : 'Server error');
        } else {
            res.writeHead(200, { 'Content-Type': contentType });
            res.end(content);
        }
    });
});

server.listen(PORT, '0.0.0.0', () => {
    log('========================================');
    log('  E2E Test Server');
    log(`  http://0.0.0.0:${PORT}`);
    log(`  Auth: ${API_KEY ? 'ENABLED' : 'DISABLED (set TESTER_API_KEY)'}`);
    log(`  Platform: ${IS_LINUX ? 'Linux/Docker' : 'Windows'}`);
    log('========================================');
});

// Graceful shutdown
process.on('SIGINT', () => {
    log('Shutdown...');
    if (testerProcess) stopTester();
    server.close(() => process.exit(0));
});
process.on('SIGTERM', () => {
    log('SIGTERM - shutdown...');
    if (testerProcess) stopTester();
    server.close(() => process.exit(0));
});
